url: "https://1ilil.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/secretwiki" # the subpath of your site, e.g. /blog
title: "Secret Wiki" # the name of your site, e.g. ACME Corp.
